FROM node:4.4.0

RUN mkdir -p /opt/emailer/app

WORKDIR /opt/emailer

RUN mkdir -p ~/.ssh
COPY id_rsa /root/.ssh/id_rsa
RUN chmod 0600 ~/.ssh/id_rsa \
  && ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY package.json ./

RUN npm install --production

COPY app/. ./app/

CMD ["node", "app/index.js"]