version: '2'

services:
  seelio-dev:
    build:
      context: seelio
      dockerfile: dev/Dockerfile_dev
    image: seelio_dev_image
    environment:
      NODE_ENV: development
    entrypoint: /bin/bash
    volumes:
      - seelio-build:/opt/seelio/build
      - ./seelio:/opt/seelio
    networks:
      - default

  hollywood:
    container_name: hollywood
    build:
      context: seelio-services/hollywood-v3
      dockerfile: Dockerfile
    env_file: ./seelio-services/hollywood-v3/hollywood.env
    ports:
      - "46559:46559"
    environment:
      NODE_ENV: development
    volumes:
      - ./seelio-services/hollywood-v3/app:/opt/hollywood/app
    networks:
      - default

  notifier:
    container_name: notifier
    build:
      context: seelio-services/notifier
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      MONGODB_CONN_STRING: 'mongodb://mongo/seelio'
    depends_on:
      - mongo
    ports:
      - "6689:6689"
    volumes:
      - ./seelio-services/notifier/app:/opt/notifier/app
    networks:
      - default

  herodotus:
    container_name: herodotus
    build:
      context: seelio
      dockerfile: dev/Dockerfile_dev
    image: seelio_dev_image
    command: "node build/libs/seelio-herodotus"
    # ports:
    #   - '4376:4376'
    depends_on:
      - notifier
      - mongo
      - redis
    environment:
      NODE_ENV: development
    volumes:
      - seelio-build:/opt/seelio/build
    networks:
      - default

  emailer:
    container_name: emailer
    build:
      context: seelio-services/emailer
      dockerfile: Dockerfile
    env_file: ./seelio-services/emailer/emailer.env
    depends_on:
      - data-access
    ports:
      - "43556:43556"
    environment:
      NODE_ENV: development
      SEELIO_LINK_HOST: localhost
      DATA_ACCESS_HOSTNAME: data-access
      SEND_ALL_EMAILS_TO: seeliotest@gmail.com
    volumes:
      - ./seelio-services/emailer/app:/opt/emailer/app
    networks:
      - default

  skillsmap:
    container_name: skillsmap
    build:
      context: skills-map
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    command: /opt/skillsmap/bin/www
    depends_on:
      - data-access
    volumes:
      - ./skills-map:/opt/skillsmap
    networks:
      - default

  data-access:
    container_name: data-access
    image: seelio/data-access:3da8790b593e1c63451c86d7c51f4130bab6ac97
    depends_on:
      - postgres
      - mongo
      - redis
    ports:
      - "9090:9090"
    env_file: ./seelio-services/data_access/data_access.env
    networks:
      - default

  postgres:
    container_name: postgres
    image: postgres:9.5.1
    ports:
      - "5432:5432"
    env_file: ./seelio-services/shared_data/postgres.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - default

  mongo:
    container_name: mongo
    image: mongo:2.6
    ports:
      - "27017:27017"
    env_file: ./seelio-services/shared_data/mongo.env
    command: --smallfiles
    volumes:
      - mongo-data:/data/db
    networks:
      - default

  redis:
    container_name: redis
    image: redis:2.8
    ports:
      - "6379:6379"
    env_file: ./seelio-services/shared_data/redis.env
    volumes:
      - redis-data:/data
    networks:
      - default

  web:
    container_name: web
    build:
      context: seelio
      dockerfile: dev/Dockerfile_dev
    image: seelio_node12
    working_dir: /opt/seelio
    command: "node build/app.js"
    ports:
      - "7754:7754"
    depends_on:
      - herodotus
      - skillsmap
      - notifier
      - data-access
      - mongo
      - redis
    environment:
      NODE_ENV: development
      AWS_ACCESS_KEY_ID: AKIAIYKIKW26ECS325UA
      AWS_SECRET_ACCESS_KEY: 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
    volumes:
      - seelio-build:/opt/seelio/build
      - ./seelio:/opt/seelio
    networks:
      - default

  nginx:
    container_name: nginx
    image: nginx:1.7
    command: nginx -c /etc/nginx/nginx.conf -g "daemon off;"
    ports:
      - "80:80"
    depends_on:
      - web
      - skillsmap
    volumes_from:
      - web
    volumes:
      - ./seelio/dev/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - default

volumes:
  postgres-data:
    driver: local
  mongo-data:
    driver: local
  redis-data:
    driver: local
  seelio-build:
    driver: local

networks:
  default:
    driver: bridge
